adminpracticas/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

app/urls.py
from django.urls import path 
from . import views 
 
app_name = 'app' 
urlpatterns = [
    #Inicio e inscripcion
    path('', views.paginadeinicio, name='paginadeinicio'), 
    path('iniciarsesion/', views.iniciarsesion, name='iniciarsesion'), #El primero es el que va a el views,el segundo es el nombre de la url
    path('salir/', views.salir, name='salir'),
    path('iniciarsesion_post/', views.post_iniciarsesion, name='post_iniciarsesion'),
    path('acercade/', views.acercade, name='acercade'),
    path('iniciarsesion/error_acceso', views.iniciarsesion_error, name='iniciarsesion_error'),
    path('error', views.error, name='error'),
    #Empresa
    path('crearempresa/', views.crearempresa, name='crearempresa'),
    path('crearempresa/f', views.crearempresa_f, name='crearempresa_f'),
    #path('crearempresa/final', views.crearempresa_final, name='crearempresa_final'),#Probar
    path('inicioempresa/', views.inicio_empresa, name='inicio_empresa'),
    path('inicioempresa/crear_conv', views.crear_conv, name='crear_conv'),
    path('inicioempresa/crear_convf', views.crear_conv_f, name='crear_conv_f'),
    #path('inicioempresa/crear_conv/final', views.crear_conv_final, name='cons_conv_final'),
    path('inicioempresa/lista_conv/', views.lista_conv_empr, name='lista_conv_empr'),
    path('inicioempresa/lista_conv/cons/<int:id>/abierta', views.cons_conv_empr_a, name='cons_conv_empr_a'),
    path('inicioempresa/lista_conv/cons/<int:id>/cerrada', views.cons_conv_empr_c, name='cons_conv_empr_c'),
    path('inicioempresa/lista_conv/cons/<int:id>/postulacion', views.editar_postulacion, name='editar_postulacion'),
    path('inicioempresa/lista_conv/conv/<int:id>/editar', views.conv_editar, name='conv_editar'),
    path('inicioempresa/lista_conv/conv/<int:id>/editar_varios', views.conv_editar_muchos, name='conv_editar_muchos'),
    path('inicioempresa/lista_conv/cons/<int:id>/editar_0', views.conv_editar_0, name='conv_editar_0'),
    path('inicioempresa/lista_conv/cons/<int:id>/editar_estado', views.conv_editar_estado, name='conv_editar_estado'),
    path('inicioempresa/cons_perf_est_empr/', views.cons_perf_est_empr, name='cons_perf_est_empr'),

    #Estudiante
    path('inicioestudiante/', views.inicio_estudiante, name='inicio_estudiante'),
    path('inicioestudiante/lista_conv_est', views.lista_conv_est, name='lista_conv_est'),
    path('inicioestudiante/cons_conv/<int:id>/aplicar', views.cons_conv_est_aplicar, name='cons_conv_est_aplicar'),
    path('inicioestudiante/cons_conv/<int:id>/aplicar_form', views.est_aplicar_form, name='est_aplicar_form'),
    #path('inicioestudiante/cons_conv/<int:id>/final', views.cons_conv_est_final, name='cons_conv_est_final'),
    path('inicioestudiante/lista_post_est/', views.lista_post_est, name='lista_post_est'),
    path('inicioestudiante/lista_post_est/<int:id>/aceptada', views.post_est_acep, name='post_est_acep'),
    path('inicioestudiante/lista_post_est/<int:id>/rechazada', views.post_est_rech, name='post_est_rech'),
    path('inicioestudiante/edit_perf_est', views.edit_perf_est, name='edit_perf_est'),
    path('inicioestudiante/edit_perf_est/final', views.edit_perf_est_final, name='edit_perf_est_final'),
    #Error por si consulta la conv y/o lista de otro:
    #path('inicioestudiante/lista_post_est/<int:id>/error', views.lista_post_est_error, name='lista_post_est_error'),
    #path('inicioestudiante/lista_post_est/info/<int:id>/error', views.info_post_est_error, name='info_post_est_error'),
    #path('inicioestudiante/edit_perf_est/<int:id>/error', views.edit_perf_est_error, name='edit_perf_est_error'),

    #Coordinador

    path('iniciocoord/', views.inicio_coord, name='inicio_coord'),
    path('iniciocoord/lista_empr', views.lista_empr, name='lista_empr'),
    path('iniciocoord/lista_empr/cons_empr/<int:id>/', views.cons_empr, name='cons_empr'),
    path('iniciocoord/lista_conv', views.lista_conv, name='lista_conv'),
    path('iniciocoord/lista_conv/cons_conv/<int:id>/abierta', views.cons_conv_a, name='cons_conv_a'),
    path('iniciocoord/lista_conv/cons_conv/<int:id>/cerrada', views.cons_conv_c, name='cons_conv_c'),
    path('iniciocoord/crear_est', views.crear_est, name='crear_est'),
    path('iniciocoord/crear_estf', views.crear_est_f, name='crear_est_f'),
    path('iniciocoord/cons_est_perf', views.cons_est_perf, name='cons_est_perf'),
    path('iniciocoord/cons_est_pract', views.cons_est_pract, name='cons_est_pract'),
    path('iniciocoord/edit_sem', views.edit_sem, name='edit_sem'),
    path('iniciocoord/edit_semf', views.edit_sem_f, name='edit_sem_f'),
    
]

app/templates/app/crearempresa.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/estilocrearempresa.css' %}">
    <title>Crear Empresa</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>
    <body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
 <script src="https://kit.fontawesome.com/f1466240f9.js" crossorigin="anonymous"></script>

 <div class="contenedor" >
    <div class="header">
        <ul class="nav nav-pills">
            <li class="nav-item" >
              <a class="nav-link " href="{% url 'app:paginadeinicio' %}">
                
                <i class="fa fa-home" ></i> Inicio</a>
            </li>
            <li class="nav-item">
              
              <a class="informacion nav-link " href="{% url 'app:acercade' %}">
                
                <i class="fa fa-info-circle" ></i> Info</a>
            </li>
            
          </ul>
    </div>
    <div class="encabezado">
        <img src="{% static 'app/img/logo_teleco.png' %}" class="logo" alt="Logo UStA">  
           <h1 class="titulo" >Crear Empresa</h1>
           
 </div>
 <div class="row">
     
 <form action="{% url 'app:crearempresa_f' %}" class="formulario" method="POST">
  {% csrf_token %}
    <div class="form-group row">
        <label for="username" class="col-2" class="col-form-label">Usuario:*</label>
        <input type="text"  name="username" placeholder="Escribe tu usuario" class="form-control col-10" required autofocus> 
        
      </div>
      <div class="form-group row">
        <label  for="password"   class="col-2" class="col-form-label">Password:*</label>
          <input type="password" name="password"  placeholder="Digita una contraseña" class="form-control col-10" required>
      </div>
      <div class="form-group row">
        <label  for="razon_social"  class="col-2" class="col-form-label" >Razón Social:*</label>
        <textarea class="area form-control col-10" name="razon_social" placeholder="Escriba la razón social de la empresa..." rows="1" required></textarea>

      </div>
      <div class="form-group row">
        <label  for="ciudad"   class="col-2" class="col-form-label">Ciudad:*</label>
          <input type="text" name="ciudad"  placeholder="Digite la ciudad de la empresa" class="form-control col-10" required>
      </div>
      <div class="form-group row">
        <label  for="email"   class="col-2" class="col-form-label">Email:*</label>
          <input type="email"  name="email"  placeholder="Digita correo electronico" class="form-control col-10" id="inputEmail4" required>
      </div>
      <div class="form-group row">
        <label  for="nombre_contacto"   class="col-2" class="col-form-label">Nombre de contacto:*</label>
          <input type="text"  name="nombre_contacto" placeholder="Escriba el nombre de contacto" class="form-control col-10" required>
      </div>
      
      <button  type="submit"  class="bregistro btn btn-success "  >
        <i class="fas fa-check"></i>  REGISTRARSE
        
      </button> 
      
      <br>
      <span class="campos">Los campos marcados con * son obligatorios.</span>
      </form>
    
    </div>

  
  <div class="footer">
    <span class="contacto">Contacto y soporte: diegoazuero@usantotomas.edu.co - USTA </span>

    </div>
</div>
</body>
</html>

app/templates/app/iniciocoordinador.html
{%extends 'app/plantcoord.html'%}
{% load static %}
{% block linkshead%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/iniciocoordinador.css' %}">
    
   
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
{% endblock %}


{% block titulo%}
<title>Inicio coordinador</title>
{% endblock %}

{% block linksbody%}
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://kit.fontawesome.com/f1466240f9.js" crossorigin="anonymous"></script>

{% endblock %}

{% block encabezado%}
<h1 class="titulo" >Bienvenido coordinador</h1>
{%endblock%}

{% block contenido%}

            <div class="row">
                <div class="col-sm-3 col-md-3">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-file text-primary">
                                    </span> Convocatorias</a>
                                </h4>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse ">
                                <div class="panel-body">
                                        
                                        <tr>
                                            <td>                                                                                
                                                <span class="glyphicon glyphicon-folder-open text-primary"></span><a href="{% url 'app:lista_conv' %}">  Lista de convocatorias</a>
                                            </td>
                                        </tr>
                                       
                                      
                                   
                                </div>
                            </div>
                            
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-briefcase text-primary">
                                    </span> Empresas</a>
                                </h4>
                            </div>
                            <div id="collapseTwo" class="panel-collapse collapse">
                                <div class="panel-body">
                                   
                                        <tr>
                                            <td>                                                                        
                                                <span class="glyphicon glyphicon-list text-info"></span>  <a href="{% url 'app:lista_empr' %}"> Lista de empresas</a> 
                                            </td>
                                        </tr>
                                       
                                       

                                   
                                </div>
                            </div>
                        </div>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="
                                        glyphicon glyphicon-user text-primary">
                                    </span> Estudiantes</a>
                                </h4>
                            </div>
                            <div id="collapseThree" class="panel-collapse collapse">
                                <div class="panel-body">
                                    <table class="table">
                                        <tr>
                                            <td>                                                                          
                                                <span class="glyphicon glyphicon-list text-info"></span>  <a href="{% url 'app:cons_est_perf' %}"> Lista de estudiantes</a> 
                                            </td>
                                        </tr>
                                       
                                        <tr>
                                            <td>
                                                <span class="glyphicon glyphicon-user text-info"></span>  <a href="{% url 'app:crear_est' %}"> Crear estudiante</a> 
                                            </td>
                                        </tr>

                                        <tr>
                                            <td>                                                                    
                                                <span class="glyphicon glyphicon-user text-info"></span>  <a href="{% url 'app:cons_est_pract' %}"> Histórico de estudiantes en 
                                                    practica</a> 
                                            </td>
                                        </tr>

                                    </table>
                                </div>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" data-parent="#accordion" href="#collapseFour"><span class="glyphicon glyphicon-cog text-primary">
                                    </span> Configuración</a>
                                </h4>
                            </div>
                            <div id="collapseFour" class="panel-collapse collapse">
                                <div class="panel-body">
                                    
                                        <tr>
                                            <td>                                                            
                                                <span class="glyphicon glyphicon-calendar"></span>  <a href="{% url 'app:edit_sem' %}"> Actualizar semestre</a> 
                                            </td>
                                        </tr>
                                   
                                </div>
                            </div>
                        </div>
                      
                    </div>
                </div>
                <div class="container" >
                <div class="col-md-10">
                    <div class="well">
                        <h1>Menu:</h1>
                        Hola coordinador {{request.user.first_name}}, por medio del menu de la barra de la izquierda puedes hacer uso de diferentes funciones como rol de coordinador.
                    </div>
                </div>
            
        </div>

        </div>

        
        <img class="logo" src="{% static 'app/img/logo_sinfondo.png' %}" alt="Logo teleco">
    
{%endblock%}

app/templates/app/listaconvempresa.html
{%extends 'app/plantempr.html'%}
{% load static %}

{% block linkshead%}

<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="{% static 'app/css/listaconvempresa.css' %}">

{% endblock %}


{% block titulo%}
<title>Lista de convocatorias</title>
{% endblock %}

{% block linksbody%}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet'
        type='text/css'>
    <script src="https://kit.fontawesome.com/f1466240f9.js" crossorigin="anonymous"></script>
{% endblock %}

{% block encabezado%}
<h1 class="titulo">Lista de mis convocatorias</h1>
{%endblock%}

{% block contenido%}
<span class="anuncio">En la siguiente tabla encontraras toda la lista de las convocatorias hechas por la
    empresa, dándole clic al lupa en la columna de consular podrás conocer más detalles sobre
    la convocatoria y sobre los postulados, si deseas realizar algún tipo de configuración da clic al
    símbolo que esta en la columna de editar. </span>

<div class="container">
    <div class="row col-md-8 col-md-offset-2 ">
        <table class="table table-bordered">
            <thead>

                <tr>
                    <th class="text-center">Nombre de la convocatoria</th>
                    <th class="text-center">Email</th>
                    <th class="text-center">Fecha de inicio</th>
                    <th class="text-center">Fecha final</th>
                    <th class="text-center">Cantidad de postulados</th>
                    <th class="text-center">Estado</th>
                    <th class="text-center">Consultar</th>
                    <th class="text-center">Editar</th>
                    
                </tr>
            </thead>
            <tbody>
                {% for conv in convocatorias   %}
                <tr>
                    <td class="text-center">{{conv.nombre}}</td>
                    <td class="text-center">{{conv.email}}</td>
                    <td class="text-center">{{conv.fecha_inicial}}</td>
                    <td class="text-center">{{ conv.fecha_final }}</td>
                    
                    <td class="text-center">{{ conv.cantidad }}</td>
                   
                    {% if conv.cerrada %}
                    <td class="cerrada text-center">Cerrada</td>
                    {% else %}
                    {% if not conv.cerrada %}
                    <td class="abierta text-center">Abierta</td>
                    {% endif %}
                    {% endif %}
                    
                    {% if conv.cerrada %}
                    <td class="text-center"><a class='btn btn-info btn-xs'
                       
                            href="{% url 'app:cons_conv_empr_c'  conv.id %}"><span
                                class="glyphicon glyphicon-search"></span> </a>
                    {% else %}
                    
                    <td class="text-center"><a class='btn btn-info btn-xs'
                       
                        href="{% url 'app:cons_conv_empr_a'  conv.id %}"><span
                            class="glyphicon glyphicon-search"></span> </a>
                    {% endif %}
                    

                    {% if conv.cantidad == 0 %}
                    <td class="text-center"><a class='btn btn-warning btn-xs'
                            href="{%  url  'app:conv_editar' conv.id %}"><span class="glyphicon glyphicon-cog"></span>
                        </a>
                        {% else %}
                        
                    <td class="text-center"><a class='btn btn-warning btn-xs'
                     href="{%  url  'app:conv_editar_muchos' conv.id %}"><span class="glyphicon glyphicon-cog"></span>
                    </a>
                    
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>

        </table>
    </div>
</div>
{%endblock%}

app/templates/app/listadeempresas.html
{%extends 'app/plantcoord.html'%}
{% load static %}
{% block linkshead%}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link rel="stylesheet" href="{% static 'app/css/listadeempresas.css' %}">
{% endblock %}


{% block titulo%}
<title>Lista de empresas</title>
{% endblock %}

{% block linksbody%}
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css" rel='stylesheet' type='text/css'>
    <script src="https://kit.fontawesome.com/f1466240f9.js" crossorigin="anonymous"></script>
{% endblock %}

{% block encabezado%}
<h1 class="titulo" >Lista de empresas</h1>
{%endblock%}

{% block contenido%}
<span class="anuncio" > A continuación se encuentran todas las empresas que están registradas en el sistema:</span>

<div class="container">
    <div class="row col-md-8 col-md-offset-2 ">
    <table class="table table-bordered">
    <thead>
    
        <tr>
            <th class="text-center">Nombre empresa</th>
            <th class="text-center">Ciudad</th>
            <th class="text-center">Nombre de contacto</th>
            <th class="text-center" >Email</th>
            <th class="text-center" >Consultar</th>
        </tr>
    </thead>
    <tbody>
        {% for empr in lista_de_empresas %}
            <tr>
                <td class="text-center">{{empr.user.username }} </td>
                <td class="text-center">{{empr.ciudad}}</td>
                <td class="text-center">{{empr.nombre_contacto}}</td>
                <td class="text-center">{{empr.user.email}}</td>
                <td class="text-center"><a class='btn btn-info btn-xs' href="{%  url  'app:cons_empr' empr.id %}"><span class="glyphicon glyphicon-search"></span> </a> 
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
    </div>
</div>
{%endblock%}

app/templates/app/paginadeinicio.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/css/estilo1.css' %}">
    <title>Administrador de practicas</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
 <script src="https://kit.fontawesome.com/f1466240f9.js" crossorigin="anonymous"></script>

    <div class="contenedor" >
        <div class="header">
            <ul class="nav nav-pills">
                <li class="nav-item" >
                  <a class="nav-link " href="{% url 'app:paginadeinicio' %}">
                    
                    <i class="fa fa-home" ></i> Inicio</a>
                </li>
                <li class="nav-item">
                  <a class="informacion nav-link " href="{% url 'app:acercade' %}">
                    
                    <i class="fa fa-info-circle" ></i> Info</a>
                </li>
                
              </ul>
        </div>
        <div class="presentacion">
            <h1 class="titulo">Administrador de practicas Ingeniería de telecomunicaciones </h1>
            <br>
            <img class="logo" src="{% static 'app/img/logo_teleco.png' %}" alt="Logo teleco"> 
          
           
        </div>
        <div class=" prueba">
            <div class="ingresar" >
                <h1 class="titulos">Ingresar al sistema.</h1>
                
                <p class="texto">
                    Si eres estudiante,coordinador o empresa y ya te encuentras registrado,dale al botón acceder.
                </p>
                <a href="{% url 'app:iniciarsesion' %}">
                <button class="boton1" >
                    <i class="icono fas fa-door-open"></i> ACCEDER
                  </button>
                </a>
                
            </div>
        </div>
        <div >
            <div class="inscripcion">
                <h1 class="titulos">Inscripción Empresa.
                </h1>
                
                <p class="texto">
                    Si eres representante de una empresa y deseas inscribirla en el sistema,oprime el botón ¡CREAR!. Después de inscribir tu empresa automáticamente quedaras registrado.
                </p>
                <a href="{% url 'app:crearempresa' %}">
                <button class="boton2" >
                    <i class="fas fa-marker"  ></i>  !CREAR¡
                  </button>
                </a>
                
            </div>

        </div>
        <div class="footer">
        <span class="contacto">Contacto y soporte: diegoazuero@usantotomas.edu.co - USTA </span>

        </div>
    </div>
    
</body>
</html>